# Generated by Django 5.2.1 on 2025-05-28 20:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exampleapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aftermath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('decision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exampleapp.decision')),
            ],
        ),
    ]
